import json, os, re
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "packs")
REC = "\n\nHinweis: Aus dem automatischen YouTube-Transkript rekonstruiert. ⚠︎ = im Video nachhören."
P = {}

P['basics-01'] = ("Basics 1 – Begrüßung & Höflichkeit", "Basics",
"Viele Begrüßungen haben eine feste Antwort:\nsbah lkhir → sbah nnur\nmsa lkhir → msa nnur\nsalamu 3likum → wa 3likum salam\n\n3afak (bitte) hängt man einfach hinten an: lma 3afak = Wasser, bitte.\n\nSCHREIBWEISE\n3 = ع → gepresster Laut aus der Kehle\n7 = ح → hartes H aus dem Hals\n9 = ق → tiefes K hinten im Rachen\nkh = wie „ch“ in „Bach“\ngh = Rachen-R wie im Französischen\nch = sch", [
("Hallo","salam",""),
("Friede sei mit dir (Begrüßung)","salamu 3likum / salam 3likum","Antwort: wa 3likum salam"),
("Guten Morgen","sbah lkhir / sba7 lkhir","Antwort: sbah nnur"),
("Guten Abend","msa lkhir","Antwort: msa nnur"),
("Wie geht's?","labas?","Antwort: labas = mir geht's gut"),
("Wie geht's dir? (zu einem Mann)","kif dayr? / kidayr?",""),
("Wie geht's dir? (zu einer Frau)","kif dayra? / kidayra?",""),
("Gut, Gott sei Dank","bikhir, lhamdulillah",""),
("Alles gut?","kolchi mzyan?",""),
("Bitte (wenn man um etwas bittet)","3afak / afak","Hinten anhängen: lma 3afak = Wasser, bitte"),
("Danke","chokran / shukran",""),
("Vielen Dank","chokran bzzaf / shukran bzzaf",""),
("Gern geschehen","bla jmil / la3fu",""),
("Entschuldigung / Verzeihung","smeh liya / smah li",""),
("Kein Problem","machi mochkil",""),
("Willkommen","mer7ba / marhba",""),
("Tschüss","bslama",""),
("Bis später","nchofek men b3d","wörtlich: ich sehe dich später"),
("Ja","iyeh / ah",""),
("Nein","la",""),
("Okay / einverstanden","wakha","Hört man ständig"),
("Genug / fertig / passt","safi",""),
("So Gott will","inchallah","Auch für „hoffentlich“ oder „mal sehen“"),
("Gott sei Dank","lhamdulillah",""),
("Wirklich? / Echt?","bse77? / bsa7?",""),
])

P['basics-02'] = ("Basics 2 – Kennenlernen & Verständigung", "Basics",
"„wach“ am Satzanfang macht aus einer Aussage eine Ja/Nein-Frage:\nnta mghribi = du bist Marokkaner → wach nta mghribi? = Bist du Marokkaner?\n\nVerneinung umklammert das Verb: ma … ch\nfhemt (ich habe verstanden) → ma fhemtch (ich habe nicht verstanden)", [
("Ich heiße …","smiti …",""),
("Wie heißt du?","chno smitek? / ach smitek?",""),
("Freut mich","metcharfin",""),
("Woher kommst du? (zu einem Mann)","mnin nta?",""),
("Woher kommst du? (zu einer Frau)","mnin nti?",""),
("Ich komme aus Deutschland","ana men lalman / ana mn almanya",""),
("Deutschland","lalman / almanya",""),
("Marokko","lmeghrib",""),
("Bist du Marokkaner?","wach nta mghribi?","„wach“ macht eine Ja/Nein-Frage"),
("Ich habe verstanden","fhemt",""),
("Ich verstehe nicht","ma fhemtch",""),
("Ich weiß nicht","ma3reftch / ma kan3refch",""),
("Sprichst du Darija? (zu einem Mann)","wach kathder darija? / wach kathder b darija?",""),
("Ich spreche ein bisschen Darija","kanhder chwiya d darija / kanhder chwiya b darija",""),
("Ich lerne Darija","kant3llem darija",""),
("Langsam, bitte","b chwiya 3afak / bchwiya 3afak",""),
("Noch einmal, bitte","3awed 3afak",""),
("Was heißt das auf Darija?","kifach katgulu hadi b darija?","⚠︎ im Kurs bestätigen lassen"),
("Wie alt bist du?","ch7al f 3mrek?",""),
("Ich bin … Jahre alt","3ndi … 3am","wörtlich: ich habe … Jahre"),
], 2)

P['basics-03'] = ("Basics 3 – Fragewörter", "Basics",
"Fragewörter stehen am Satzanfang: fin kayn ssu9? = Wo ist der Markt?", [
("Was?","chno? / ach?",""),
("Wer?","chkun?",""),
("Wo?","fin?",""),
("Wann?","imta?",""),
("Warum?","3lach?",""),
("Wie?","kifach?",""),
("Wie viel? / Wie viele?","ch7al?",""),
("Wie viel kostet das?","bch7al hada? / bchhal hada?","Beim Einkaufen: bch7al = für wie viel"),
("Woher?","mnin?",""),
("Welche(r)?","achmen? / ina?",""),
("Was ist das?","chno hada?",""),
("Wo ist …?","fin kayn …?",""),
("Gibt es …?","wach kayn …?",""),
("Was machst du? (zu einem Mann)","chno kaddir?",""),
("Was willst du? (zu einem Mann)","chno bghiti?",""),
("Hast du …? (zu einem Mann)","wach 3ndek …?",""),
])

P['basics-04'] = ("Basics 4 – Zahlen", "Basics",
"11–19 enden auf -tach, die Zehner auf -in.\nZwischen Zahl und Sache steht oft „d“: jouj d atay = zwei Tee.\n\nVorsicht beim Einkaufen: Preise werden oft in Rial statt Dirham genannt (1 Dirham = 20 Rial). Im Zweifel nachfragen: bdrahm? = in Dirham?", [
("0 / null","sifr",""),
("1 / eins","wa7ed / wahed",""),
("2 / zwei","jouj / juj",""),
("3 / drei","tlata",""),
("4 / vier","rb3a / rab3a",""),
("5 / fünf","khamsa",""),
("6 / sechs","stta / setta",""),
("7 / sieben","sb3a / seb3a",""),
("8 / acht","tmnya / tmanya",""),
("9 / neun","ts3ud / tes3ud",""),
("10 / zehn","3chra / 3achra",""),
("11 / elf","7dach",""),
("12 / zwölf","tnach",""),
("13 / dreizehn","tlettach / tlttach",""),
("14 / vierzehn","rb3tach",""),
("15 / fünfzehn","khmstach / khamstach",""),
("16 / sechzehn","settach / sttach",""),
("17 / siebzehn","sb3tach",""),
("18 / achtzehn","tmentach / tmntach",""),
("19 / neunzehn","ts3tach / tsa3tach",""),
("20 / zwanzig","3chrin / 3ichrin",""),
("30 / dreißig","tlatin",""),
("40 / vierzig","rb3in",""),
("50 / fünfzig","khamsin",""),
("100 / hundert","mya / miya",""),
("1000 / tausend","alf",""),
])

P['basics-05'] = ("Basics 5 – Zeit & Wochentage", "Basics",
"Vor Wochentage setzt man oft „nhar“ (Tag): nhar ssebt = (am) Samstag.", [
("heute","lyum / lyoum",""),
("morgen","ghedda",""),
("gestern","lbar7",""),
("jetzt","daba",""),
("später","men b3d",""),
("immer","dima",""),
("manchmal","chi merrat / mrra mrra",""),
("Tag","nhar",""),
("Woche","simana / ssimana",""),
("Monat","chher",""),
("Jahr","3am",""),
("Vormittag / früh am Tag","sba7",""),
("Abend","l3chiya",""),
("Nacht","lil",""),
("Wie spät ist es?","ch7al f sa3a?",""),
("Montag","letnin / nhar letnin",""),
("Dienstag","tlat / nhar tlat",""),
("Mittwoch","larb3 / nhar larb3",""),
("Donnerstag","lkhmis / nhar lkhmis",""),
("Freitag","jjem3a / nhar jjem3a",""),
("Samstag","ssebt / nhar ssebt",""),
("Sonntag","l7edd / nhar l7edd",""),
])

P['basics-06'] = ("Basics 6 – Kleine Wörter", "Basics",
"VERNEINUNG\n• Verben: ma … ch → ma bghitch (ich will nicht)\n• Vor Adjektiven und Nomen: machi → machi mzyan (nicht gut)\n\nhada = dieser/das (männlich) · hadi = diese (weiblich) · hadchi = das hier / das Zeug", [
("es gibt","kayn",""),
("es gibt nicht","makaynch",""),
("ein bisschen","chwiya",""),
("viel / sehr","bzzaf",""),
("alles","kolchi",""),
("nichts","walo",""),
("hier","hna",""),
("dort","temma / lhih",""),
("mit","m3a",""),
("und","w",""),
("aber","walakin",""),
("oder","wla / ola",""),
("nicht (vor Adjektiv oder Nomen)","machi","machi mzyan = nicht gut"),
("auch","7tta / tta","ta ana = ich auch"),
("vielleicht","ymken",""),
("schnell","dghya / bzerba",""),
("dieser / das (männlich)","hada",""),
("diese (weiblich)","hadi",""),
("das hier / das Zeug","hadchi",""),
("ich habe","3ndi",""),
("du hast","3ndek",""),
("ich habe nicht","ma3ndich",""),
("mein / meine","dyali","hada dyali = das ist meins"),
])

P['basics-07'] = ("Basics 7 – Wichtige Verben", "Basics",
"Alle Karten in der ich-Form im Präsens: ana + kan- + Grundform (wie in Video 1). Das „ana“ kann man auch weglassen. In der Notiz steht die Grundform bzw. der Imperativ.\n\nAusnahme bghit (ich will): sieht aus wie Vergangenheit, bedeutet aber Gegenwart.\nkhassni + Verb = ich muss: khassni nmchi = ich muss gehen.", [
("ich gehe","ana kanmchi","Geh! = sir"),
("ich komme","ana kanji","Komm! = aji"),
("ich will / ich möchte","ana bghit","Vergangenheitsform mit Gegenwartsbedeutung"),
("ich will nicht","ana ma bghitch",""),
("ich muss / ich brauche","khassni","khassni nmchi = ich muss gehen"),
("ich kann","ana kan9der / ana n9der",""),
("ich weiß","ana kan3ref",""),
("ich mache","ana kandir","Mach! = dir"),
("ich arbeite","ana kankhdem","Arbeite! = khdem"),
("ich wohne","ana kanskon","Wo wohnst du? = fin katskon?"),
("ich lerne","ana kant3llem",""),
("ich gebe","ana kan3ti","Gib mir! = 3tini"),
("ich nehme","ana kanakhod / ana kankhod","Nimm! = khod"),
("ich warte","ana kantsenna","Warte! = tsenna"),
("ich mag / ich liebe","ana kanbghi","kanbghik = ich liebe dich"),
("ich schreibe","ana kanekteb / ana kanktb","Schreib! = kteb"),
("ich lese","ana kan9ra","Lies! = 9ra"),
("ich setze mich / ich bleibe","ana kangles","Setz dich! = gles"),
("ich öffne","ana kan7ell","Mach auf! = 7ell"),
("ich schließe","ana kansedd","Mach zu! = sedd"),
], 2)

P['basics-08'] = ("Basics 8 – Essen, Café & Markt", "Basics",
"Bestellen ist einfach: bghit … 3afak = Ich möchte …, bitte.\nbghit nss nss 3afak = Einen Milchkaffee, bitte.", [
("Wasser","lma",""),
("Brot","lkhobz",""),
("Kaffee","l9ahwa / qahwa",""),
("Milchkaffee (halb-halb)","nss nss / nos nos","Typische Bestellung im Café"),
("Milch","l7lib",""),
("Zucker","sokkar / sukkar",""),
("ohne Zucker","bla sokkar / bla sukkar",""),
("Fleisch","l7em",""),
("Hähnchen","djaj / ddjaj",""),
("Fisch","l7ut",""),
("Gemüse","lkhodra",""),
("Obst","lfakya",""),
("Salz","lmel7",""),
("Ei","bida",""),
("lecker","bnin",""),
("Ich habe Hunger","fiya ljou3 / ana ji3an",""),
("Ich habe Durst","fiya l3tech / ana 3tchan",""),
("Die Rechnung, bitte","l7sab 3afak",""),
("Ich möchte das","bghit hadchi",""),
("zu teuer","ghali bzzaf",""),
("billig","rkhis",""),
("Geld","flus / flous",""),
("Geh etwas runter mit dem Preis (beim Handeln)","n9es chwiya",""),
])

P['basics-09'] = ("Basics 9 – Familie & Menschen", "Basics",
"„mein/meine“ hängt oft direkt am Wort: khti = meine Schwester, sa7bi = mein Freund.", [
("meine Mutter","mmi / lwalida",""),
("mein Vater","bba / lwalid",""),
("mein Bruder","khuya / khoya",""),
("meine Schwester","khti",""),
("mein Sohn","weldi",""),
("meine Tochter","benti",""),
("Kind","drri",""),
("Kinder","drari",""),
("Mann","rajel",""),
("Frau","mra",""),
("mein Mann","rajli",""),
("meine Frau","mrati",""),
("Familie","l3a2ila / l3ayla",""),
("mein Freund (Kumpel)","sa7bi",""),
("meine Freundin (Kumpelin)","sa7bti",""),
("Junge","weld",""),
("Mädchen","bent",""),
("Leute","nnas",""),
])

P['basics-10'] = ("Basics 10 – Orte & Wege", "Basics",
"Nach dem Weg fragen: fin kayn …? = Wo ist …?\nAntwort oft: nichan, men b3d 3la limen = geradeaus, dann rechts.", [
("Haus","ddar",""),
("Straße / Gasse","zzen9a / triq",""),
("Stadt","lmdina",""),
("Markt","ssu9 / souk",""),
("Laden","l7anut",""),
("Toilette","lbit lma / twalit",""),
("Wo ist die Toilette?","fin kayn lbit lma?",""),
("Moschee","jjame3",""),
("Meer","lb7er",""),
("Bahnhof","lagar",""),
("Flughafen","lmatar",""),
("nach rechts","3la limen",""),
("nach links","3la chmal / 3la lisser",""),
("geradeaus","nichan",""),
("nah","9rib",""),
("weit","b3id",""),
])

P['basics-11'] = ("Basics 11 – Adjektive", "Basics",
"Weibliche Form: meist -a anhängen: mzyan → mzyana, kbir → kbira.\nDas Adjektiv steht hinter dem Nomen: ddar kbira = das große Haus.", [
("gut","mzyan","f: mzyana"),
("schlecht","khayb","f: khayba"),
("schön","zwin","f: zwina"),
("groß","kbir","f: kbira"),
("klein","sghir","f: sghira"),
("heiß","s7un / sokhon",""),
("kalt","bared",""),
("neu","jdid",""),
("alt (Sachen)","9dim",""),
("müde","3iyan",""),
("glücklich / froh","fer7an",""),
("krank","mrid",""),
("satt","chb3an",""),
("einfach","sahel",""),
("schwierig","s3ib",""),
("voll","3amer",""),
("leer","khawi",""),
])


def conj(de_forms, da_forms, notes=None):
    notes = notes or [""] * 8
    return [(d, a, n) for d, a, n in zip(de_forms, da_forms, notes)]

YT1_NOTES = json.load(open(f"{OUT}/yt-01.json"))["notes"]
P['yt-01'] = ("Grammatik 1 – Pronomen, Schreibweise & Präsens", "Grammatik", YT1_NOTES, [
("ich","ana",""),
("du (zu einem Mann)","nta",""),
("du (zu einer Frau)","nti",""),
("er","howa / huwa",""),
("sie (Singular)","hiya",""),
("wir","7na","7 = ح, hartes H aus dem Hals"),
("ihr","ntuma / ntoma",""),
("sie (Plural)","huma / homa",""),
("Hemd","9amija","9 = ق, tiefes K hinten im Rachen · ⚠︎ Beispiel unsicher"),
("hässlich","khayb / khayeb","kh = wie „ch“ in „Bach“"),
("Kamel","jmel","j wie in „Journal“ · ⚠︎ Beispiel unsicher"),
("Iss! (Grundform: essen)","kul","Wird auch gesagt, wenn man jemandem Essen anbietet"),
("Trink! (Grundform: trinken)","chrob",""),
("Fahr! (Grundform: fahren)","sug / sog",""),
] + conj(
  ["ich esse","du isst (m)","du isst (f)","er isst","sie isst","wir essen","ihr esst","sie essen (Plural)"],
  ["ana kanakul","nta katakul","nti katakli","howa kayakul","hiya katakul","7na kanaklu","ntuma kataklu","huma kayaklu"],
  ["ana → kan-","nta → kat-","nti → kat- … -i","howa → kay-","hiya → kat- (wie nta)","7na → kan- … -u","ntuma → kat- … -u","huma → kay- … -u"]
) + conj(
  ["ich trinke","du trinkst (m)","du trinkst (f)","er trinkt","sie trinkt","wir trinken","ihr trinkt","sie trinken (Plural)"],
  ["ana kanchrob","nta katchrob","nti katchrbi","howa kaychrob","hiya katchrob","7na kanchrbu","ntuma katchrbu","huma kaychrbu"]
) + conj(
  ["ich fahre","du fährst (m)","du fährst (f)","er fährt","sie fährt","wir fahren","ihr fahrt","sie fahren (Plural)"],
  ["ana kansug","nta katsug","nti katsugi","howa kaysug","hiya katsug","7na kansugu","ntuma katsugu","huma kaysugu"]
) + [
("Tee","atay","Marokkanischer Minztee"),
("Ich trinke Tee","ana kanchrob atay","Meist ohne „ana“: kanchrob atay"),
], 4)

P['yt-02'] = ("Grammatik 2 – Neue Verben & Futur (ghadi / gha)", "Grammatik",
"NEUE VERBEN (Grundform)\nn3es = schlafen · chri = kaufen · hder = sprechen · chouf = sehen\nl3eb = spielen · tyyeb = kochen · sifet = schicken\n\n3 = ع → gepresster Laut tief aus der Kehle\nIn tyyeb steckt ein ط – ein dumpfes T, irgendwo zwischen D und T.\n\nFUTUR – zwei gleichwertige Formen\n1) ghadi + Präsens ohne ka-\n   kan- → n- · kat- → t- · kay- → y-\n   ghadi passt sich an: ghadi (m) · ghadya (f) · ghadyin (Plural)\n   ana ghadi nakul · nti ghadya takli · 7na ghadyin naklu\n2) gha- direkt vors Verb, bleibt immer gleich\n   ana ghanakul · nti ghatakli · 7na ghanaklu\n\nAls Frau sagt man selbst: ana ghadya nakul." + REC, [
("Schlaf! (Grundform: schlafen)","n3es","3 = ع, gepresster Kehllaut"),
("Kauf! (Grundform: kaufen)","chri",""),
("Sprich! (Grundform: sprechen)","hder",""),
("Schau! (Grundform: sehen)","chouf / chuf",""),
("Spiel! (Grundform: spielen)","l3eb",""),
("Koch! (Grundform: kochen)","tyyeb / tiyeb","Das t ist ein ط – dumpf, zwischen D und T"),
("Schick! (Grundform: schicken)","sifet","⚠︎ im Video nachhören"),
("Couscous","kesksu / kseksu",""),
("Fußball","lkora",""),
("viel","bzzaf",""),
("Ich koche Couscous","ana kantyyeb kesksu",""),
("Wir spielen Fußball","7na kanl3bu lkora",""),
("Ihr kauft viel ein","ntuma katchriw bzzaf","Verben auf -i bekommen im Plural -w statt -u"),
] + conj(
  ["ich werde essen","du wirst essen (m)","du wirst essen (f)","er wird essen","sie wird essen","wir werden essen","ihr werdet essen","sie werden essen (Plural)"],
  ["ana ghadi nakul / ana ghanakul","nta ghadi takul / nta ghatakul","nti ghadya takli / nti ghatakli","howa ghadi yakul / howa ghayakul","hiya ghadya takul / hiya ghatakul","7na ghadyin naklu / 7na ghanaklu","ntuma ghadyin taklu / ntuma ghataklu","huma ghadyin yaklu / huma ghayaklu"],
  ["Als Frau: ana ghadya nakul","","","","","","",""]
) + [
("Ich werde Couscous kochen","ana ghadi ntyyeb kesksu / ana ghantyyeb kesksu",""),
("Wir werden Fußball spielen","7na ghadyin nl3bu lkora / 7na ghanl3bu lkora",""),
("Ihr werdet viel einkaufen","ntuma ghadyin tchriw bzzaf / ntuma ghatchriw bzzaf",""),
], 4)

P['yt-03'] = ("Grammatik 3 – Vergangenheit", "Grammatik",
"NEUE VERBEN (Grundform)\ndir = machen · khdem = arbeiten · 3um = schwimmen · kteb = schreiben · khud = nehmen\n\nVERGANGENHEIT – zwei Formen\n\n1) Mit kan (war) + Präsensform\n   ana kunt · nta/nti kunti · howa kan · hiya kanet\n   7na kunna · ntuma kuntu · huma kanu\n   ana kunt kanakul = ich war am Essen / ich aß (früher)\n\n2) Ohne kan: Grundform + Endung (im Alltag häufiger)\n   ana -t · nta/nti -ti · howa – · hiya -at\n   7na -na · ntuma -tu · huma -u\n   ana chrebt, nta chrebti, howa chreb, hiya chrbat, 7na chrebna, ntuma chrebtu, huma chrbu\n\nAUSNAHME: Verben mit i/u in der Mitte (dir, sug, 3um …)\n   Bei ich/du/wir/ihr wird daraus ein e, bei er/sie/sie (Pl.) ein a:\n   dert, derti, dar, dart, derna, dertu, daru\n\nNeues Wort: ktab = Buch" + REC, [
("Mach! (Grundform: machen)","dir",""),
("Arbeite! (Grundform: arbeiten)","khdem",""),
("Schwimm! (Grundform: schwimmen)","3um",""),
("Schreib! (Grundform: schreiben)","kteb",""),
("Nimm! (Grundform: nehmen)","khud / khod","⚠︎ im Video nachhören"),
("Buch","ktab / lktab",""),
] + conj(
  ["ich war","du warst (m)","du warst (f)","er war","sie war","wir waren","ihr wart","sie waren (Plural)"],
  ["ana kunt","nta kunti","nti kunti","howa kan","hiya kanet / hiya kant","7na kunna","ntuma kuntu","huma kanu"]
) + [
("ich war am Essen / ich aß (früher)","ana kunt kanakul","kan + Präsensform"),
("er war am Essen","howa kan kayakul",""),
] + conj(
  ["ich habe getrunken","du hast getrunken (m)","du hast getrunken (f)","er hat getrunken","sie hat getrunken","wir haben getrunken","ihr habt getrunken","sie haben getrunken (Plural)"],
  ["ana chrebt","nta chrebti","nti chrebti","howa chreb","hiya chrbat","7na chrebna","ntuma chrebtu","huma chrbu"],
  ["Endung -t","Endung -ti","Endung -ti (wie bei nta)","keine Endung","Endung -at","Endung -na","Endung -tu","Endung -u"]
) + conj(
  ["ich habe gemacht","du hast gemacht (m)","du hast gemacht (f)","er hat gemacht","sie hat gemacht","wir haben gemacht","ihr habt gemacht","sie haben gemacht (Plural)"],
  ["ana dert","nta derti","nti derti","howa dar","hiya dart","7na derna","ntuma dertu","huma daru"],
  ["Ausnahme: i → e","","","Ausnahme: i → a","","","",""]
) + [
("Ich habe Couscous gekocht","ana tyyebt kesksu / ana kunt kantyyeb kesksu","Beide Formen gehen"),
("Wir haben Fußball gespielt","7na l3bna lkora / 7na kunna kanl3bu lkora",""),
("Ihr habt viel eingekauft","ntuma chritu bzzaf / ntuma kuntu katchriw bzzaf",""),
("Ich habe ein Buch genommen","ana khdit ktab / ana kunt kanakhod ktab","⚠︎ im Video nachhören"),
], 4)

P['yt-04'] = ("Grammatik 4 – Nomen: Geschlecht, Plural & Artikel", "Grammatik",
"GESCHLECHT\nWörter auf -a sind (fast immer) feminin: lamba, kelma, tabla, kora, kuzina.\nAlles andere ist maskulin: kelb, bit, kursi, weld, rajel.\nAchtung: tabla (Tisch) ist feminin – anders als im Deutschen.\n\nWEIBLICHE FORM: +a\nkelb → kelba · ustad → ustada · tbib → tbiba\nGilt auch für Adjektive: rajel zwin · mra zwina\nDas Adjektiv steht hinter dem Nomen.\n\nPLURAL\nFeminin: +t → lambat, kelmat, tablat, korat, tomobilat\nMaskulin: keine Regel, immer mitlernen!\nkelb → klab · bit → byut · kursi → krasa · weld → wlad · rajel → rjal\n\nARTIKEL\nder/die/das = l- vorne dran, für alles gleich: lkuzina, lbit, lktab\nVor t, d, s, z, r, n, ch u. a. verschmilzt das l mit dem Anfang: ttabla, rrajel, nnas, ddar\nein/eine = wa7ed + l-: wa7ed lkuzina (wörtlich „eine die Küche“)\n\nDIESER / DIESE\nVor einem Nomen: had (m und f gleich) → had lktab, had rrajel, had lmra\nAllein stehend: hada (m) · hadi (f) · hadu (Plural)" + REC, [
("Lampe","lamba","feminin (endet auf -a) · ⚠︎ im Video nachhören"),
("Wort","kelma","feminin"),
("Tisch","tabla / tbla","feminin – anders als im Deutschen"),
("Ball","kora","feminin"),
("Auto","tomobila / tomobil","feminin"),
("Küche","kuzina / kozina","feminin"),
("Hund","kelb","maskulin · Plural: klab"),
("Zimmer","bit","maskulin · Plural: byut"),
("Stuhl","kursi","maskulin · Plural: krasa"),
("Hündin","kelba","kelb + a"),
("Lehrer","ustad / ostad",""),
("Lehrerin","ustada / ostada","ustad + a"),
("Arzt","tbib","⚠︎ im Video nachhören"),
("Ärztin","tbiba","tbib + a"),
("schwarz","k7el","f: k7la"),
("schöner Mann","rajel zwin","Adjektiv steht hinter dem Nomen"),
("schöne Frau","mra zwina","weiblich → zwin + a"),
("großes Zimmer","bit kbir",""),
("große Küche","kuzina kbira",""),
("schwarzer Stuhl","kursi k7el",""),
("schwarzer Tisch","tabla k7la","tabla ist feminin → k7la"),
("Lampen","lambat","Feminin-Plural: +t"),
("Wörter","kelmat",""),
("Tische","tablat",""),
("Bälle","korat",""),
("Autos","tomobilat",""),
("Hunde","klab","Maskulin-Plural: einzeln lernen"),
("Zimmer (Plural)","byut",""),
("Stühle","krasa","⚠︎ im Video nachhören"),
("Jungen (Plural)","wlad","Singular: weld"),
("Männer","rjal","Singular: rajel"),
("die Küche","lkuzina","Artikel l- gilt für der, die und das"),
("das Zimmer","lbit",""),
("der Tisch","ttabla","Vor t verschmilzt das l: ttabla"),
("der Mann","rrajel","Vor r verschmilzt das l: rrajel"),
("eine Küche","wa7ed lkuzina","ein/eine = wa7ed + Artikel"),
("ein Tisch","wa7ed ttabla",""),
("dieser / diese / dieses (vor einem Nomen)","had","Für m und f gleich"),
("dieser hier (allein, männlich)","hada",""),
("diese hier (allein, weiblich)","hadi",""),
("diese hier (Plural)","hadu","⚠︎ im Video nachhören"),
("dieses Buch","had lktab",""),
("dieser Mann","had rrajel","Das l hört man hier kaum"),
("diese Frau","had lmra","Hier hört man das l deutlich"),
], 2)

P['yt-05'] = ("Grammatik 5 – Besitz (mein, dein …) & mir/dir", "Grammatik",
"ENDUNGEN – brauchst du überall\n-i = mein · -ek = dein · -o = sein · -ha = ihr\n-na = unser · -kum = euer · -hum = ihr (Plural)\n\nBESITZ – zwei Formen\n\n1) Allein stehend: dyal + Endung (das ist meins …)\n   Sache männlich: dyali, dyalek, dyalo, dyalha, dyalna, dyalkum, dyalhum\n   Sache weiblich: t vor die Endung → dyalti, dyaltek, dyalto …\n   (Im Alltag hört man oft auch dyali für beides.)\n   had lkuzina dyalti = diese Küche ist meine\n\n2) Direkt am Wort\n   männlich: Endung dran → ktabi, ktabek, ktabo …\n   weiblich: -a weg, dann t + Endung → tomobila → tomobilti, tomobiltek …\n   kuzinti sghira = meine Küche ist klein\n\nMIR / DIR / IHM … (mir und mich sind gleich)\nDieselben Endungen, z. B. -ni = mir/mich, -ek = dir/dich\n3jeb = gefallen\n   Sache männlich → kay3jebni · Sache weiblich → kat3jebni\n   lmeghrib kay3jebni = Marokko gefällt mir\n   almanya kat3jebni = Deutschland gefällt mir (endet auf -a → weiblich)\nghadi nzurek = ich werde dich besuchen (zur = besuchen)" + REC, [
("meins (Sache männlich)","dyali","Endung -i"),
("deins (Sache männlich)","dyalek","Endung -ek"),
("seins (Sache männlich)","dyalo / dyalu","Endung -o"),
("ihrs – von ihr (Sache männlich)","dyalha","Endung -ha"),
("unseres (Sache männlich)","dyalna","Endung -na"),
("eures (Sache männlich)","dyalkum","Endung -kum"),
("ihres – von ihnen (Sache männlich)","dyalhum","Endung -hum"),
("meins (Sache weiblich)","dyalti","t vor die Endung · im Alltag oft auch dyali"),
("deins (Sache weiblich)","dyaltek",""),
("seins (Sache weiblich)","dyalto / dyaltu",""),
("ihrs – von ihr (Sache weiblich)","dyaltha",""),
("unseres (Sache weiblich)","dyaltna",""),
("eures (Sache weiblich)","dyaltkum",""),
("ihres – von ihnen (Sache weiblich)","dyalthum",""),
("mein Buch","ktabi","ktab + i"),
("dein Buch","ktabek",""),
("sein Buch","ktabo / ktabu",""),
("ihr Buch (von ihr)","ktabha",""),
("unser Buch","ktabna",""),
("euer Buch","ktabkum",""),
("ihr Buch (von ihnen)","ktabhum",""),
("mein Auto","tomobilti","tomobila: -a weg, t + Endung"),
("dein Auto","tomobiltek",""),
("sein Auto","tomobilto / tomobiltu",""),
("ihr Auto (von ihr)","tomobiltha",""),
("unser Auto","tomobiltna",""),
("euer Auto","tomobiltkum",""),
("ihr Auto (von ihnen)","tomobilthum",""),
("Handy / Telefon","tilifun / portable","maskulin (kein -a am Ende)"),
("Meine Küche ist klein","kuzinti sghira","kuzina: -a weg, t + i"),
("Diese Küche ist meine","had lkuzina dyalti",""),
("Dein Handy ist schön","tilifunek zwin",""),
("Dieses Handy ist deins","had ttilifun dyalek",""),
("gefällt mir (Sache männlich)","kay3jebni","Endung -ni = mir/mich"),
("gefällt mir (Sache weiblich)","kat3jebni","weiblich → kat-"),
("gefällt dir","kay3jbek",""),
("gefällt ihm","kay3jbo",""),
("gefällt ihr","kay3jbha",""),
("gefällt uns","kay3jebna",""),
("gefällt euch","kay3jebkum",""),
("gefällt ihnen","kay3jebhum",""),
("Marokko gefällt mir","lmeghrib kay3jebni",""),
("Deutschland gefällt mir","almanya kat3jebni","almanya endet auf -a → weiblich → kat-"),
("Dieses Buch gefällt mir","had lktab kay3jebni",""),
("Ich werde dich besuchen","ana ghadi nzurek / ana ghanzurek","zur = besuchen, -ek = dich"),
("Ich werde euch besuchen","ana ghadi nzurkum / ana ghanzurkum","-kum = euch"),
], 2)

P['yt-06'] = ("Basics 4b – Zahlen bis 99", "Basics",
"0–12 haben eigene Namen (siehe Basics 4 – Zahlen).\n\n13–19: Zahl 3–9 + -tach, die Endung fällt weg\ntlata → tlettach · rb3a → rb3tach · khamsa → khmstach · stta → settach\nsb3a → sb3tach · tmnya → tmntach · ts3ud → ts3tach\n\n21–99: Einer + u (und) + Zehner – wie im Deutschen „einundzwanzig“\nwa7ed u 3chrin = 21 · tlata u tlatin = 33\nAchtung: Bei der 2 nimmt man tnin statt jouj → tnin u 3chrin = 22\nGeschrieben wird es meist zusammen; u und w sind dasselbe.\n\nZEHNER\n20 3chrin · 30 tlatin · 40 rb3in · 50 khamsin\n60 sttin · 70 sb3in · 80 tmanin · 90 tes3in" + REC, [
("und (bei Zahlen)","u / w","wa7ed u 3chrin = 21"),
("zwei (in 22, 32, 42 …)","tnin","Statt jouj!"),
("60 / sechzig","sttin",""),
("70 / siebzig","sb3in",""),
("80 / achtzig","tmanin",""),
("90 / neunzig","tes3in / ts3in",""),
("21 / einundzwanzig","wa7ed u 3chrin","Einer + u + Zehner"),
("22 / zweiundzwanzig","tnin u 3chrin","tnin statt jouj"),
("23 / dreiundzwanzig","tlata u 3chrin",""),
("25 / fünfundzwanzig","khamsa u 3chrin",""),
("32 / zweiunddreißig","tnin u tlatin",""),
("37 / siebenunddreißig","sb3a u tlatin",""),
("44 / vierundvierzig","rb3a u rb3in",""),
("51 / einundfünfzig","wa7ed u khamsin",""),
("58 / achtundfünfzig","tmnya u khamsin",""),
("63 / dreiundsechzig","tlata u sttin",""),
("69 / neunundsechzig","ts3ud u sttin",""),
("72 / zweiundsiebzig","tnin u sb3in",""),
("76 / sechsundsiebzig","stta u sb3in",""),
("85 / fünfundachtzig","khamsa u tmanin",""),
("88 / achtundachtzig","tmnya u tmanin",""),
("91 / einundneunzig","wa7ed u tes3in",""),
("99 / neunundneunzig","ts3ud u tes3in",""),
], 2)

P['yt-07'] = ("Grammatik 6 – Fragen stellen & antworten", "Grammatik",
"W-FRAGEN\nDas Fragewort steht immer vorne: mnin nta? = Woher kommst du?\nchno / ach = was · chkun = wer · fin = wo · mnin = woher · imta = wann\n3lach = warum · achmen = welche(r) · ch7al = wie viel · kifach = wie\n\nkifach nimmt man nur, wenn eine Erklärung folgt:\nkifach dertiha? = Wie hast du das gemacht? → dertha hakka = So habe ich es gemacht.\n\nALTER fragt man mit „wie viel“: ch7al f 3mrek?\nAntwort: 3ndi 3chrin 3am – oft reicht einfach die Zahl: 3chrin.\n\nJA/NEIN-FRAGEN\nwach vorne dran: wach nta talib? = Bist du Student?\nOder nur mit fragendem Tonfall: nta talib?\nAntwort: iyeh, ana talib · la, ana machi talib\n\nBERUFE: weiblich +a → talib / taliba" + REC, [
("so (auf diese Weise)","hakka",""),
("Wie hast du das gemacht? (zu einem Mann)","kifach dertiha? / kifach derti hadchi?","kifach = wie, wenn eine Erklärung folgt"),
("Ich habe es so gemacht","dertha hakka",""),
("in","f / fi","f dortmund = in Dortmund"),
("Wo wohnst du? (zu einem Mann)","fin katskon?",""),
("Ich wohne in Dortmund","ana kanskon f dortmund",""),
("Wohnst du in Dortmund? (zu einem Mann)","wach katskon f dortmund?","wach = Ja/Nein-Frage"),
("Was arbeitest du? (zu einem Mann)","chno katkhdem?",""),
("Student","talib","Auch oft: etudiant (französisch)"),
("Studentin","taliba","Berufe: weiblich +a"),
("Ich bin Student","ana talib",""),
("Ich bin Studentin","ana taliba",""),
("Bist du Student?","wach nta talib?","Geht auch nur mit Frageton: nta talib?"),
("Ja, ich bin Student","iyeh, ana talib",""),
("Nein, ich bin kein Student","la, ana machi talib","machi = nicht/kein vor Nomen"),
("Ich bin 20 (Jahre alt)","3ndi 3chrin 3am / 3chrin","Oft reicht einfach die Zahl"),
("Wer bist du? (zu einem Mann)","chkun nta?","⚠︎ im Video nachhören"),
("Welches Buch?","achmen ktab?",""),
("weil","7it / 7itach",""),
("Wann kommst du? (zu einem Mann)","imta ghadi tji?",""),
])

P['yt-08'] = ("Grammatik 7 – Sätze mit Adjektiven", "Grammatik",
"„IST / SIND“ FÄLLT WEG\nNomen mit Artikel + Adjektiv ohne Artikel = ganzer Satz\nssak jdid = Die Tasche ist neu\nNomen mit Artikel + Adjektiv mit Artikel = „die neue Tasche“\nssak ljdid = die neue Tasche\n\nARTIKEL-VERDOPPLUNG\nBeginnt ein Wort mit d, n, r, s, t, z (u. a.), wird statt l der erste Buchstabe verdoppelt:\nssak · ddar · rrjal · ttomobilat\n\nADJEKTIV ANPASSEN – Beispiel fer7an (fröhlich)\nmännlich fer7an · weiblich fer7ana\nPlural männlich fer7anin · Plural weiblich fer7anat\nViele Adjektive haben zusätzlich einen eigenen Plural – beide Formen gehen:\nsghir → sghar / sghirin · kbir → kbar / kbirin · jdid → jdad / jdidin\n\nAUSNAHME: i als 3. Buchstabe wird zu y\nghali → ghalya · ghalyin · ghalyat\nzwin bleibt trotzdem regelmäßig: zwina · zwinin · zwinat\n\nACHTUNG\nkbir heißt groß UND alt (bei Menschen): rrjal kbar = Die Männer sind alt\ndar (Haus) ist weiblich, obwohl es nicht auf -a endet: ddar 9riba" + REC, [
("Tasche","sak","maskulin"),
("Die Tasche ist neu","ssak jdid","Adjektiv ohne Artikel = Satz mit „ist“"),
("die neue Tasche","ssak ljdid / ssak jjdid","Adjektiv mit Artikel"),
("Die Stadt ist nah","lmdina 9riba","lmdina ist weiblich → 9riba"),
("Die Zimmer sind klein","lbyut sghar / lbyut sghirin","Beide Pluralformen gehen"),
("die kleinen Zimmer","lbyut ssghar / lbyut ssghirin","Adjektiv mit Artikel → s verdoppelt"),
("Die Autos sind groß","ttomobilat kbar / ttomobilat kbirat","⚠︎ im Video nachhören"),
("fröhlich (m)","fer7an",""),
("fröhlich (f)","fer7ana","+a"),
("fröhlich (Plural m)","fer7anin","+in"),
("fröhlich (Plural f)","fer7anat","+at"),
("teuer (m)","ghali",""),
("teuer (f)","ghalya","Ausnahme: i wird zu y"),
("teuer (Plural m)","ghalyin",""),
("teuer (Plural f)","ghalyat",""),
("schön (Plural m)","zwinin","zwin bleibt regelmäßig"),
("schön (Plural f)","zwinat",""),
("klein (Plural)","sghar / sghirin",""),
("groß / alt (Plural)","kbar / kbirin","kbir = groß, bei Menschen auch alt"),
("neu (Plural)","jdad / jdidin",""),
("billig (Plural)","rkhas / rkhisin","⚠︎ im Video nachhören"),
("schwer (Gewicht)","t9il","f: t9ila"),
("traurig","7zin / m9elle9","⚠︎ im Video nachhören"),
("Das Buch ist neu","lktab jdid",""),
("Das Haus ist nah","ddar 9riba","dar ist weiblich, obwohl ohne -a"),
("Die Männer sind alt","rrjal kbar / rrjal kbirin","kbir = groß und alt"),
("Die Autos sind klein","ttomobilat sghar / ttomobilat sghirat",""),
])


# ---------- Wortschatz aus dem Darija Open Dataset (DODa) ----------
DODA = "\n\nQuelle: Darija Open Dataset (DODa), github.com/darija-open-dataset/dataset – Lizenz CC BY-NC 4.0. Auswahl, deutsche Übersetzung und Schreibweise für diese App angepasst, einzelne Beispielsätze ergänzt."

P['doda-farben'] = ("Wortschatz – Farben", "Wortschatz",
"Farben sind Adjektive und stehen hinter dem Nomen: tomobila 7amra = ein rotes Auto.\nWeibliche Form: 7mer → 7amra · khder → khedra · zre9 → zer9a · byed → bida · k7el → k7la · sfer → sefra" + DODA, [
("Farbe","lun / lawn",""),
("rot","7mer","f: 7amra"),
("grün","khder","f: khedra"),
("blau","zre9","f: zer9a"),
("weiß","byed","f: bida"),
("schwarz","k7el","f: k7la"),
("gelb","sfer","f: sefra"),
("orange","limuni","wörtlich: orangenfarben"),
("grau","gri",""),
("braun","9ahwi","wörtlich: kaffeefarben"),
("rosa","wardi","wörtlich: rosenfarben"),
("lila","banafsaji / 9u9i",""),
("golden","dhbi",""),
("dunkel (bei Farben)","mghlu9","zre9 mghlu9 = dunkelblau"),
("hell (bei Farben)","meftu7","zre9 meftu7 = hellblau"),
("ein rotes Auto","tomobila 7amra","tomobila ist weiblich → 7amra"),
])

P['doda-koerper'] = ("Wortschatz – Körper", "Wortschatz",
"„Mein …“ hängt direkt am Wort (Grammatik 5): ras → rasi = mein Kopf.\nSchmerzen: … kayderrni = … tut mir weh → rasi kayderrni = Mein Kopf tut weh." + DODA, [
("Kopf","ras",""),
("Gesicht","wjeh",""),
("Auge","3in","Plural: 3inin"),
("Ohr","wden",""),
("Nase","nif / mnakher",""),
("Mund","fomm",""),
("Zahn","senna","Plural: snan"),
("Zunge","lsan",""),
("Haare","ch3er",""),
("Bart","l7ya",""),
("Hals / Nacken","3n9 / 3ng",""),
("Schulter","ktef",""),
("Arm","dra3",""),
("Hand","yedd",""),
("Finger","sbe3",""),
("Bein / Fuß","rjel",""),
("Knie","rokba",""),
("Rücken","dhar",""),
("Bauch","kerch",""),
("Herz","9alb",""),
("Blut","dem",""),
("Körper","jasad",""),
("mein Kopf","rasi","ras + i"),
("Mein Kopf tut weh","rasi kayderrni","kayderrni = tut mir weh"),
])

P['doda-kleidung'] = ("Wortschatz – Kleidung", "Wortschatz", "Kleidung anziehen: lbes → ana kanlbes = ich ziehe an (siehe Verben: unterwegs & Alltag)." + DODA, [
("Kleidung","7wayej",""),
("Hose","serwal",""),
("Schuhe","sebbat",""),
("Socken","t9acher",""),
("Mantel","kebbot",""),
("Jacke","jakita",""),
("Rock","saya",""),
("Kleid","kswa",""),
("Schal","chal",""),
("Kappe / Mütze","kaskita",""),
("Gürtel","smta",""),
("Ring","khatem",""),
("Geldbeutel","bztam",""),
("Regenschirm","mdell",""),
("Tasche (an der Kleidung)","jib",""),
("Djellaba (langes Gewand mit Kapuze)","jellaba",""),
("Babuschen (Lederpantoffeln)","belgha",""),
("Kaftan","9eftan",""),
])

P['doda-tiere'] = ("Wortschatz – Tiere", "Wortschatz", "Hund (kelb), Kamel (jmel) und Fisch (l7ut) kennst du schon aus anderen Lektionen." + DODA, [
("Tier","7ayawan",""),
("Katze","mech",""),
("Esel","7mar",""),
("Pferd","3awd",""),
("Kuh","bgra",""),
("Schaf","khruf / 7awli","7awli = Hammel, z. B. zum Opferfest"),
("Ziege","m3za",""),
("Huhn","djaja",""),
("Hahn","ferruj",""),
("Vogel","3sfur / twiyer",""),
("Taube","7mama",""),
("Storch","bellarj",""),
("Maus","far",""),
("Schildkröte","fekrun",""),
("Schlange","7ench",""),
("Skorpion","3e9reb",""),
("Ameise","nemla",""),
("Fliege","debbana",""),
("Mücke","namusa",""),
("Biene","n7la",""),
("Löwe","sbe3",""),
("Affe","9erd",""),
])

P['doda-gemuese'] = ("Wortschatz – Gemüse, Obst & Kräuter", "Wortschatz", "Auf dem Markt: bghit kilo d maticha 3afak = Ein Kilo Tomaten, bitte." + DODA, [
("Zwiebel","basla",""),
("Tomate","maticha",""),
("Kartoffel","btata / batata",""),
("Karotte","khizzu",""),
("Gurke","khyar",""),
("Knoblauch","tuma / ttuma",""),
("Paprika","felfla",""),
("Aubergine","denjal",""),
("Kürbis","gar3a",""),
("Bohnen","lubya",""),
("Kichererbsen","7ammes",""),
("Linsen","3des",""),
("Oliven","zitun",""),
("Koriander","9zbur",""),
("Petersilie","m3dnus",""),
("Minze","n3na3","Gehört in jeden atay"),
("Apfel","tfa7",""),
("Banane","banan",""),
("Orange","limun","Achtung: limun = Orange, 7amed = Zitrone"),
("Zitrone","7amed",""),
("Weintrauben","3neb",""),
("Wassermelone","dlla7 / dela7",""),
("Erdbeeren","friz",""),
("Feigen","kermus",""),
("Datteln","tmer",""),
("Mandeln","luz",""),
])

P['doda-essen'] = ("Wortschatz – Mahlzeiten & Geschmack", "Wortschatz", "Geschmack beschreiben wie jedes Adjektiv: atay 7lu = Der Tee ist süß." + DODA, [
("das Essen","makla",""),
("Frühstück","ftur",""),
("Mittagessen","ghda",""),
("Abendessen","3cha",""),
("Öl","zit",""),
("Butter","zebda",""),
("Käse","fromaj",""),
("Saft","3asir",""),
("Harira (Suppe)","7rira","Typische Suppe, besonders im Ramadan"),
("Salat","chlada",""),
("Tajine","tajin",""),
("Gewürze","3triya",""),
("Kreuzkümmel","kamun",""),
("Zimt","9erfa",""),
("süß","7lu",""),
("scharf","7arr",""),
("sauer","7amed","Gleiches Wort wie „Zitrone“"),
("bitter","merr",""),
("gegrillt","mechwi",""),
("frittiert","m9li",""),
("Guten Appetit! / Zum Wohl!","bssa7tek / bssa7a",""),
])

P['doda-wetter'] = ("Wortschatz – Wetter & Natur", "Wortschatz", "Übers Wetter reden mit kayn (es gibt): kayn sehd = es ist heiß, kayn lberd = es ist kalt, kayna chta = es regnet." + DODA, [
("Wetter","t9es",""),
("Sonne","chems / chemch",""),
("Mond","9mer / l9mer",""),
("Stern","nejma",""),
("Himmel","sma",""),
("Regen","chta",""),
("Schnee","telj",""),
("Wind","ri7",""),
("Hitze","sehd",""),
("Kälte","lberd",""),
("Es ist heiß (Wetter)","kayn sehd / kayn ssehd",""),
("Es ist kalt (Wetter)","kayn lberd",""),
("Es regnet","kayna chta",""),
("Winter","chtwa",""),
("Sommer","sif / ssif",""),
("Herbst","lkhrif",""),
("Frühling","rbi3 / rrbi3",""),
("Berg","jbel",""),
("Fluss","wad",""),
("Baum","chejra",""),
("Wald","ghaba",""),
("Wüste","s7ra",""),
("Sand","rmla",""),
("Stein","7jer",""),
])

P['doda-berufe'] = ("Wortschatz – Berufe", "Wortschatz",
"Weibliche Form meist +a: serbay → serbaya (Grammatik 4).\nmol = „der mit …“: mol taxi = Taxifahrer, mol l7ut = Fischverkäufer.\nArzt (tbib), Lehrer (ustad) und Student (talib) kennst du schon." + DODA, [
("Arbeit","khedma",""),
("Krankenpfleger / Krankenschwester","fermli / fermliya",""),
("Ingenieur","mohandis",""),
("Anwalt","mo7ami",""),
("Polizist","bulisi",""),
("Kellner","serbay",""),
("Kellnerin","serbaya",""),
("Friseur","7ejjam",""),
("Metzger","gezzar",""),
("Gemüsehändler","khddar",""),
("Schreiner","njjar",""),
("Fahrer","chifur",""),
("Taxifahrer","mol taxi",""),
("Fischverkäufer","mol l7ut",""),
("Mechaniker","mikanisyan",""),
("Elektriker","trisyan",""),
("Klempner","plombi",""),
("Bauer","fella7",""),
("Angestellter","mowaddaf",""),
("Journalist","sa7afi",""),
("Chef / Direktor","mudir",""),
("Schneider","khiyat",""),
])

P['doda-gesundheit'] = ("Wortschatz – Gesundheit", "Wortschatz", "Schmerzen: rasi kayderrni = Mein Kopf tut weh (siehe Wortschatz – Körper)." + DODA, [
("Krankenhaus","sbitar",""),
("Apotheke","farmasyan / frmasyan",""),
("Medikament","dwa",""),
("Krankenwagen","labilans",""),
("gesund","s7i7",""),
("Gesundheit","sa77a",""),
("Fieber","skhana",""),
("Husten","k7ba",""),
("Grippe / Erkältung","rwa7",""),
("Kopfschmerzen","sda3",""),
("Schmerz","alam",""),
("Wunde","jer7a",""),
("Allergie","7asasiya",""),
("Ich bin krank","ana mrid","Als Frau: ana mrida"),
("Ich brauche einen Arzt","khassni tbib",""),
("Gute Besserung!","lah yechfik",""),
])

P['doda-praep'] = ("Wortschatz – Präpositionen", "Wortschatz",
"Viele Präpositionen nehmen die Besitz-Endungen an (Grammatik 5): m3a → m3aya = mit mir, m3ak = mit dir.\n3nd = bei: 3ndi = bei mir → „ich habe“." + DODA, [
("auf / über","3la",""),
("von / aus","men",""),
("zu / für","l",""),
("bei","3nd","3ndi = bei mir = ich habe"),
("oben drauf","fu9",""),
("unter","t7t",""),
("vor (Ort)","gddam",""),
("hinter","mura",""),
("neben","7da",""),
("zwischen","bin",""),
("vor (Zeit)","9bel",""),
("nach (Zeit)","men b3d",""),
("bis","7tta",""),
("drinnen","dakhel",""),
("draußen","kharej",""),
("ohne","bla","bla sokkar = ohne Zucker"),
("wie (vergleichend)","b7al",""),
("mit mir","m3aya",""),
("mit dir","m3ak",""),
])

P['doda-uhrzeit'] = ("Wortschatz – Uhrzeit, Kalender & Monate", "Wortschatz",
"UHRZEIT\nch7al f sa3a? = Wie spät ist es?\nu rb3 = Viertel nach · u ness = halb · llarob3 = Viertel vor\ntlata u ness = 3:30 · khamsa u rb3 = 5:15 · stta llarob3 = 5:45\nAchtung: „halb vier“ heißt auf Darija „drei und halb“ (tlata u ness).\n\nMONATE\nIm Alltag oft einfach nummeriert: chher wa7ed = Januar, chher jouj = Februar …" + DODA, [
("Sekunde","tanya",""),
("Minute","d9i9a",""),
("Stunde / Uhr","sa3a",""),
("halbe Stunde","ness sa3a",""),
("Viertelstunde","rob3 sa3a",""),
("Viertel nach","u rb3",""),
("halb (nach der Stunde)","u ness","tlata u ness = halb vier"),
("Viertel vor","llarob3",""),
("halb vier (3:30)","tlata u ness","Darija zählt: drei und halb"),
("Viertel nach fünf (5:15)","khamsa u rb3",""),
("Viertel vor sechs (5:45)","stta llarob3",""),
("um drei Uhr","f ttlata","f = um"),
("Mittag","wst nhar","wörtlich: Mitte des Tages"),
("vorgestern","wellbar7",""),
("übermorgen","b3d ghedda",""),
("Wochenende","wikand",""),
("Zeit","w9t",""),
("Januar","yanayer / chher wa7ed",""),
("Februar","fbrayer / chher jouj",""),
("März","mars / chher tlata",""),
("April","abril / chher rb3a",""),
("Mai","may / chher khamsa",""),
("Juni","yunyu / chher stta",""),
("Juli","yulyuz / chher sb3a",""),
("August","ghucht / chher tmnya",""),
("September","chutanbir / chher ts3ud",""),
("Oktober","oktobr / chher 3chra",""),
("November","nuwanbir / chher 7dach",""),
("Dezember","dujanbir / chher tnach",""),
])

P['doda-woerter'] = ("Wortschatz – Kleine Wörter 2", "Wortschatz", "Ergänzt Basics 6 – Kleine Wörter." + DODA, [
("oft / meistens","ghaliban",""),
("bald","9riban",""),
("früh","bekri",""),
("noch / immer noch","mazal","mazal ma … = noch nicht"),
("wieder / nochmal","3awtani",""),
("überhaupt nicht","ga3","ma bghitch ga3 = ich will überhaupt nicht"),
("zusammen","mjmu3in",""),
("genug","kafi",""),
("fast / ungefähr","t9riban",""),
("sofort","flblasa",""),
("leider","lil2asaf",""),
("besonders","khususan",""),
("normalerweise","3adatan",""),
("selten","nadiran",""),
("oben (im Haus)","lfu9",""),
])

P['doda-verben-alltag'] = ("Wortschatz – Verben: unterwegs & Alltag", "Wortschatz", "Wie Basics 7: ich-Form im Präsens (ana kan- + Grundform), die Grundform (Imperativ) steht in der Notiz." + DODA, [
("ich gehe hinein","ana kandkhol","Geh rein! = dkhol"),
("ich gehe hinaus","ana kankhrej","Geh raus! = khrej"),
("ich komme zurück","ana kanrje3","Komm zurück! = rje3"),
("ich komme an","ana kanwsel",""),
("ich steige aus / gehe runter","ana kanzel","Steig aus! = nzel"),
("ich stehe auf","ana kannod","Steh auf! = nod"),
("ich reise","ana kansafer",""),
("ich gehe spazieren","ana kantmechcha",""),
("ich renne","ana kanjri","Renn! = jri"),
("ich wasche","ana kanghsel","Wasch! = ghsel"),
("ich ziehe an (Kleidung)","ana kanlbes","Zieh an! = lbes"),
("ich bringe","ana kanjib","Bring! = jib · jib liya = bring mir"),
("ich lege hin / stelle hin","ana kan7ett","Leg hin! = 7ett"),
("ich suche","ana kan9elleb","kan9elleb 3la … = ich suche …"),
("ich finde","ana kanl9a",""),
("ich bezahle","ana kankhelles","Bezahl! = khelles"),
("ich schaue zu / sehe fern","ana kantferrej",""),
])

P['doda-verben-reden'] = ("Wortschatz – Verben: reden, denken, fühlen", "Wortschatz", "Wie Basics 7: ich-Form im Präsens (ana kan- + Grundform), die Grundform (Imperativ) steht in der Notiz." + DODA, [
("ich höre","ana kansme3","Hör zu! = sme3"),
("ich rufe / rufe an","ana kan3iyet","Ruf an! = 3iyet"),
("ich frage","ana kansowel",""),
("ich antworte","ana kanjaweb",""),
("ich helfe","ana kan3awen","3awenni = hilf mir"),
("ich fange an","ana kanbda",""),
("ich mache fertig / beende","ana kansali",""),
("ich vergesse","ana kansa","nsit = ich habe vergessen"),
("ich denke nach","ana kanfekker",""),
("ich erinnere mich","ana kantfekker",""),
("ich lache","ana kand7ek",""),
("ich weine","ana kanbki",""),
("ich singe","ana kanghenni",""),
("ich tanze","ana kanchte7",""),
("ich liebe (jemanden / etwas)","ana kan7ebb","Basics 7: kanbghi – beides geht"),
])


# „sie“ ist im Deutschen doppeldeutig: Karten mit hiya/huma eindeutig beschriften
def clarify(de, da, note):
    if re.match(r'^hiya\b', da):
        de = de.replace(' (Singular)', '')
        if '(eine Frau)' not in de: de += ' (eine Frau)'
        hint = 'hiya = sie, eine Frau'
    elif re.match(r'^(huma|homa)\b', da):
        de = de.replace('(Plural)', '(mehrere)')
        hint = 'huma = sie, mehrere'
    else:
        return de, da, note
    return de, da, f"{hint} · {note}" if note else hint

for pid, (title, src, notes, cards, *ver) in P.items():
    cards = [clarify(*c) for c in cards]
    json.dump({"id": pid, "version": ver[0] if ver else 1, "title": title, "notes": notes, "cards": [list(c) for c in cards]},
              open(f"{OUT}/{pid}.json", "w"), ensure_ascii=False, indent=1)

order = ['basics-01','basics-02','yt-01','basics-03','basics-04','yt-02','basics-05','basics-06','yt-03','basics-07','basics-08','yt-04','basics-09','yt-05','basics-10','yt-06','basics-11','yt-07','yt-08',
         'doda-farben','doda-koerper','doda-kleidung','doda-tiere','doda-gemuese','doda-essen','doda-wetter',
         'doda-berufe','doda-gesundheit','doda-praep','doda-uhrzeit','doda-woerter','doda-verben-alltag','doda-verben-reden']
index, total = [], 0
for pid in order:
    d = json.load(open(f"{OUT}/{pid}.json"))
    n = len(d['cards']); total += n
    src = P[pid][1]
    index.append({"id": pid, "version": d.get('version', 1), "title": d['title'], "source": f"{src} · {n} Karten", "file": f"{pid}.json"})
json.dump(index, open(f"{OUT}/index.json", "w"), ensure_ascii=False, indent=1)
print(len(index), "Pakete,", total, "Karten")
